all:
	@ echo "Nothing..."

copy-programs:
	cp ../../test/prog1/compiled/prog1.mem programs/prog1.mem
	cp ../../test/prog2/compiled/prog2.mem programs/prog2.mem
	cp ../../test/prog3/compiled/prog3.mem programs/prog3.mem